def isolated_cells(width: int, height: int) -> list[tuple[int, int]]:
    return [
        (width // 2 - 3, height // 2 - 2),
        (width // 2 - 3, height // 2 - 1),
        (width // 2 - 3, height // 2),
        (width // 2 - 2, height // 2),
        (width // 2 - 1, height // 2),
        (width // 2 - 1, height // 2 + 1),
        (width // 2 - 1, height // 2 + 2),
        (width // 2 + 3, height // 2 + 2),
        (width // 2 + 2, height // 2 + 2),
        (width // 2 + 1, height // 2 + 2),
        (width // 2 + 1, height // 2 + 1),
        (width // 2 + 1, height // 2),
        (width // 2 + 2, height // 2),
        (width // 2 + 3, height // 2),
        (width // 2 + 3, height // 2 - 1),
        (width // 2 + 3, height // 2 - 2),
        (width // 2 + 2, height // 2 - 2),
        (width // 2 + 1, height // 2 - 2),
    ]
